version: '3.8'

services:
  web:
    build: ./services/web
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    volumes:
      - ./services/web/instance/:/usr/src/app/instance
  rabbitmq:
    image: "rabbitmq:management"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build:
      context: ./services/web
    environment:
      CELERY_APP: main.celery
    command: celery -A main.celery worker --loglevel=info
    volumes:
      - ./services/web/:/usr/src/app/
    depends_on:
      - rabbitmq
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - ./services/nginx:/etc/nginx/conf.d/
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./services/certbot/conf:/etc/letsencrypt
      - ./services/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
